### ISSUE TITLE
Upgrade web3 library to latest v1

### ISSUE THREAD

**Issue by andregoncalves** [SelfKeyFoundation/Identity-Wallet#1507]

**Comment by andregoncalves** [comment]
@sk91 this is something we should do, right?

**Comment by sk91** [comment]
- Major updates to our interactions with blockchain
- fixes #1871 

For QA:
need to test all blockchain interactions and communication with KYCC using private key/trezor/ledger
 - unlock wallet
  - send eth
  - send tokens
  - add/remove new tokens
  - create did
  - marketplace applications
  - marketplace payments
  - etc...

**Comment by rhdelima** [comment]
@sk91 @andregoncalves Please see initial list of issues. Currently, I'm unable to test bank account.

**SelfKey Profile**
   - Setup your SelfKey Identity screen is no longer displayed. It directly opens SelfKey Profile if user clicks on profile avatar on upper right or click on My Profile on the left navigation. http://recordit.co/Wsqdv5CcuU



**Ledger**:
    - No confirm authentication displayed on ledger
http://recordit.co/nJ5u33o64e
![image](https://user-images.githubusercontent.com/10294014/73429392-8c768180-4376-11ea-8762-15bdb778597b.png)

**TREZOR**
   - Send transaction failed
http://recordit.co/IXmu8HlEDb
![image](https://user-images.githubusercontent.com/10294014/73429963-d744c900-4377-11ea-84e4-506422aee598.png)

**Comment by sk91** [comment]
FOR QA:
- trezor issue should be fixed
- please confirm if the issue occurs on mac for ledger, if it's only on windows, please open a separate bug for it, otherwise fail this one, I could not reproduce this on mac
- selfkey profile is issue does not reproduce, if you see it again, please open a separate issue

**Comment by sk91** [comment]
- ledger issue should also be fixed now

**Comment by andregoncalves** [comment]
Great work

**Comment by rhdelima** [comment]
Still failed on my end. Ledger works with Ledger Live but not with SK wallet.

http://recordit.co/OS9b2Hnenh

**Comment by andregoncalves** [comment]
@rhdelima @sk91 this is fixed now, right?

**Comment by rhdelima** [comment]
yep. This is good now. Closing...
